version: '3'
services:
  postfix:
    build: .
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    volumes: 
      - "./conf.d/main.cf:/etc/postfix/main.cf"
      - "./vhosts:/var/spool/vhosts"